# Documentation at https://goreleaser.com
version: 2
project_name: editorconfig-checker
env:
  - REPO_LICENSE=MIT
  - DOCKERHUB_USERNAME={{ if index .Env "DOCKERHUB_USERNAME"  }}{{ .Env.DOCKERHUB_USERNAME }}{{ else }}mstruebing{{ end }}
  - GHCR_USERNAME={{ if index .Env "GHCR_USERNAME"  }}{{ .Env.GHCR_USERNAME }}{{ else }}editorconfig-checker{{ end }}
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "editorconfig-checker"
    main: ./cmd/editorconfig-checker
    binary: editorconfig-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - arm
      - '386'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser

universal_binaries:
  - replace: true

archives:
  - id: archive-editorconfig-checker
    ids:
      - editorconfig-checker
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{- .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - tar.gz
          - zip

nfpms:
  - vendor: Editorconfig-Checker
    homepage: https://editorconfig-checker.github.io/
    maintainer: Max Strübing <mxstrbng@gmail.com>
    description: |-
      A tool to verify that your files are in harmony with your .editorconfig
    license: "{{ .Env.REPO_LICENSE }}"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

dockers_v2:
  - id: docker-linux-amd64
    ids:
      - editorconfig-checker
    dockerfile: Dockerfile
    images:
      - "{{ .Env.DOCKERHUB_USERNAME }}/editorconfig-checker"
      - "ghcr.io/{{ .Env.GHCR_USERNAME }}/editorconfig-checker"
    tags:
      - latest
      - "{{ .Version }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.description: A tool to verify that your files are in harmony with your .editorconfig"
      org.opencontainers.image.licenses: "{{ .Env.REPO_LICENSE }}"

checksum:
  name_template: "checksums.txt"
sboms:
  - artifacts: package
    id: sbom-package
  - artifacts: archive
    id: sbom-archive
  - artifacts: binary
    id: sbom-binary
  - artifacts: source
    id: sbom-source

changelog:
  use: github
  sort:
    asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  mode: keep-existing
  use_existing_draft: true
  prerelease: auto
  header: |
    ## editorconfig-checker {{ .Tag }} ({{ .Date }})

    Welcome to this new release of editorconfig-checker!
  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
