.\" Generated with help2man.
.TH EDITORCONFIG-CHECKER "1" "User Commands"
.SH NAME
editorconfig-checker \- tool to verify that your files are in harmony with your .editorconfig
.SH DESCRIPTION
.SS "USAGE:"
.HP
\fB\-config\fR string
.IP
config
.HP
\fB\-debug\fR, \fB\-v\fR, \fB\-verbose\fR
.IP
print debugging information
.HP
\fB\-disable\-end\-of\-line\fR
.IP
disables the trailing whitespace check
.HP
\fB\-disable\-indent\-size\fR
.IP
disables only the indent\-size check
.HP
\fB\-disable\-indentation\fR
.IP
disables the indentation check
.HP
\fB\-disable\-insert\-final\-newline\fR
.IP
disables the final newline check
.HP
\fB\-disable\-trim\-trailing\-whitespace\fR
.IP
disables the trailing whitespace check
.HP
\fB\-dry\-run\fR
.IP
show which files would be checked
.HP
\fB\-exclude\fR string
.IP
a regex which files should be excluded from checking \- needs to be a valid regular expression
.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
print the help
.HP
\fB\-ignore\-defaults\fR
.IP
ignore default excludes
.HP
\fB\-init\fR
.IP
creates an initial configuration
.HP
\fB\-no\-color\fR
.IP
dont print colors
.HP
\fB\-version\fR
.IP
print the version number
